@isTest
public class AccountOperationsTest {

	@isTest static void  testDefaultHasDefaultDescription(){
		//perform test
		Test.startTest();
			Account acc = new Account(Name='Test Account');
			Database.SaveResult result = Database.insert(acc);
		Test.stopTest();
		//verify
		Account savedAcc = [SELECT Description FROM Account WHERE  Id = :result.getId()];
		System.assertEquals('Default Description', savedAcc.Description);
	}
}